"use client";

import { useTheme } from "@/context/ThemeContext";
import { Card } from "@/components/ui";

// Shared empty state component
function EmptyState({ icon, title, subtitle }) {
  const { tokens: tk } = useTheme();
  return (
    <div
      style={{
        display: "flex", flexDirection: "column",
        alignItems: "center", justifyContent: "center",
        padding: "48px 24px", textAlign: "center",
        background: "#fafafa", borderRadius: 16,
        border: "1.5px dashed #e0e0e0",
      }}
    >
      <div style={{ fontSize: 36, marginBottom: 12 }}>{icon}</div>
      <div style={{ fontSize: 15, fontWeight: 700, color: "#333", marginBottom: 6 }}>{title}</div>
      <div style={{ fontSize: 13, color: "#888", lineHeight: 1.5, maxWidth: 280 }}>{subtitle}</div>
    </div>
  );
}

export default function FeedSection({ onTabChange }) {
  const { tokens: tk, tournament } = useTheme();

  return (
    <div style={{
      display: "grid",
      gridTemplateColumns: `1fr ${tk.layout.sidebarWidth}px`,
      gap: tk.spacing.xl,
      alignItems: "start",
    }}>

      {/* Main column */}
      <div style={{ display: "flex", flexDirection: "column", gap: tk.spacing.lg }}>

        {/* Current match placeholder */}
        <EmptyState
          icon="🏏"
          title="No live IPL match right now"
          subtitle="When IPL matches are live, real-time scores, win probability, and AI insights will appear here."
        />

        {/* AI insights placeholder */}
        <EmptyState
          icon="🤖"
          title="AI insights coming soon"
          subtitle="Match-specific insights generated by KrixAI will appear here as the season gets underway."
        />
      </div>

      {/* Sidebar */}
      <div style={{ display: "flex", flexDirection: "column", gap: tk.spacing.lg, position: "sticky", top: tk.spacing.section }}>

        {/* Quick Ask — always available */}
        <Card hover={false} style={{ padding: tk.spacing.lg }}>
          <div style={{ fontSize: tk.fontSize.lg, fontWeight: tk.fontWeight.semibold, marginBottom: tk.spacing.md }}>
            ✨ Quick Ask
          </div>
          <div
            onClick={() => onTabChange("chat")}
            style={{
              display: "flex", gap: tk.spacing.sm, padding: tk.spacing.md,
              background: tk.page.inputBg, borderRadius: tk.radius.xxl,
              cursor: "pointer", alignItems: "center",
            }}
          >
            <div style={{
              width: 30, height: 30, borderRadius: 15,
              background: tournament.gradient,
              display: "flex", alignItems: "center", justifyContent: "center",
              fontSize: 11, color: "#fff", fontWeight: tk.fontWeight.bold,
            }}>AI</div>
            <span style={{ fontSize: tk.fontSize.md, color: tk.page.textDim }}>
              Ask KrixAI anything...
            </span>
          </div>
        </Card>

        {/* Form ratings — empty state */}
        <Card hover={false} style={{ padding: tk.spacing.lg }}>
          <div style={{ fontSize: tk.fontSize.lg, fontWeight: tk.fontWeight.semibold, marginBottom: tk.spacing.md + 2 }}>
            🔥 Form Ratings
          </div>
          <div style={{ fontSize: 13, color: "#aaa", textAlign: "center", padding: "20px 0" }}>
            Player ratings load with live match data
          </div>
        </Card>

        {/* Schedule — empty state */}
        <Card hover={false} style={{ padding: tk.spacing.lg }}>
          <div style={{ fontSize: tk.fontSize.lg, fontWeight: tk.fontWeight.semibold, marginBottom: tk.spacing.md + 2 }}>
            📅 Schedule
          </div>
          <div style={{ fontSize: 13, color: "#aaa", textAlign: "center", padding: "20px 0" }}>
            Upcoming fixtures will appear here
          </div>
        </Card>
      </div>
    </div>
  );
}
